# Generated by Django 5.2 on 2025-05-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('num_casa', models.IntegerField()),
                ('sexo', models.TextField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')])),
                ('renda', models.TextField(blank=True, choices=[('Menos de 1 salário mínimo', 'Menos de 1 salário mínimo'), ('De 1 a 2 salários mínimos', 'De 1 a 2 salários mínimos'), ('De 2 a 3 salários mínimos', 'De 2 a 3 salários mínimos'), ('De 3 a 4 salários mínimos', 'De 3 a 4 salários mínimos'), ('De 4 a 5 salários mínimos', 'De 4 a 5 salários mínimos'), ('Mais de 5 salários mínimos', 'Mais de 5 salários mínimos')], null=True)),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.TextField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo')], null=True)),
                ('etnia', models.TextField(blank=True, choices=[('Branca', 'Branca'), ('Pardo', 'Pardo'), ('Preta', 'Preta'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena')], null=True)),
                ('escolaridade', models.TextField(blank=True, choices=[('Analfabeto', 'Analfabeto'), ('Fundamental incompleto', 'Fundamental incompleto'), ('Fundamental completo', 'Fundamental completo'), ('Médio incompleto', 'Médio incompleto'), ('Médio completo', 'Médio completo'), ('Superior incompleto', 'Superior incompleto'), ('Superior completo', 'Superior completo')], null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('nacionalidade', models.CharField(max_length=30)),
                ('deficiencia', models.BooleanField(default=False)),
                ('num_dependentes', models.IntegerField(blank=True, default=0, null=True)),
                ('religiao', models.CharField(blank=True, choices=[('Católica', 'Católica'), ('Evangélica', 'Evangélica'), ('Espírita', 'Espírita'), ('Umbanda', 'Umbanda'), ('Candomblé', 'Candomblé'), ('Sem religião', 'Sem religião')], max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DadosCenso',
        ),
    ]
