# Generated by Django 5.2 on 2025-05-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0002_morador_delete_dadoscenso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100)),
                ('resposta', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
