# Generated by Django 5.2 on 2025-05-14 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0003_indicadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('especie', models.TextField(blank=True, choices=[('Domicilio particular permanentemente', 'DOMICÍLIO PARTICULAR PERMANENTE OCUPADO'), ('Domicilio particular improvisado ocupado', 'DOMICÍLIO PARTICULAR IMPROVISADO OCUPADO'), ('Domicilio coletivo com morador', 'DOMICÍLIO COLETIVO COM MORADOR')], null=True)),
                ('tipo', models.TextField(choices=[('Casa', 'Casa'), ('Casa de vila ou em condomínio', 'Casa de vila ou em condomínio'), ('Apartamento', 'Apartamento'), ('Habitação em casa de cômodos ou cortiço', 'Habitação em casa de cômodos ou cortiço'), ('Habitação indígena sem paredes ou maloca', 'Habitação indígena sem paredes ou maloca'), ('Estrutura residencial permanente degradada ou inacabada', 'Estrutura residencial permanente degradada ou inacabada'), ('Tenda ou barraca de lona, plástico ou tecido', 'Tenda ou barraca de lona, plástico ou tecido'), ('Dentro do estabelecimento em funcionamento', 'Dentro do estabelecimento em funcionamento'), ('Outros (abrigos naturais e outras estruturas improvisadas)', 'Outros (abrigos naturais e outras estruturas improvisadas)'), ('Estrutura improvisada em logradouro público, exceto tenda ou barraca', 'Estrutura improvisada em logradouro público, exceto tenda ou barraca'), ('Estrutura não residencial permanente degradada ou inacabada', 'Estrutura não residencial permanente degradada ou inacabada'), ('Veículos (carros, caminhões, trailers, barcos etc.)', 'Veículos (carros, caminhões, trailers, barcos etc.)'), ('Asilo ou outra instituição de longa permanência para idosos', 'Asilo ou outra instituição de longa permanência para idosos'), ('Hotel ou pensão', 'Hotel ou pensão'), ('Alojamento', 'Alojamento'), ('Penitenciária, centro de detenção e similar', 'Penitenciária, centro de detenção e similar'), ('Outro', 'Outro'), ('Abrigo, albergue ou casa de passagem para população em situação de rua', 'Abrigo, albergue ou casa de passagem para população em situação de rua'), ('Abrigo, casas de passagem ou república assistencial para outros grupos vulneráveis', 'Abrigo, casas de passagem ou república assistencial para outros grupos vulneráveis'), ('Clínica psiquiátrica, comunidade terapêutica e similar', 'Clínica psiquiátrica, comunidade terapêutica e similar'), ('Orfanato e similar', 'Orfanato e similar'), ('Unidade de internação de menores', 'Unidade de internação de menores'), ('Quartel ou outra organização militar', 'Quartel ou outra organização militar')])),
                ('quantidade_comodos', models.IntegerField()),
                ('acesso_internet', models.BooleanField(default=False)),
                ('abastecimento_agua', models.TextField(choices=[('Rede geral de distribuição', 'Rede geral de distribuição'), ('Poço artesiano', 'Poço artesiano'), ('Cacimba', 'Cacimba'), ('Rio, lago, córregos ou represas', 'Rio, lago, córregos ou represas'), ('fonte, nascente ou mina', 'fonte, nascente ou mina'), ('carro-pipa', 'carro-pipa'), ('água de chuva', 'água de chuva'), ('Outro', 'Outro')])),
                ('coleta_esgoto', models.TextField(choices=[('Rede geral de esgoto', 'Rede geral de esgoto'), ('Fossa séptica', 'Fossa séptica'), ('Fossa rudimentar', 'Fossa rudimentar'), ('Rio, lago, córregos ou represas', 'Rio, lago, córregos ou represas'), ('Vala', 'Vala'), ('Outro', 'Outro')])),
                ('distribuicao_agua', models.TextField(choices=[('Encanada até dentro da moradia', 'Encanada até dentro da moradia'), ('Encanada, mas apenas terreno ou quintal', 'Encanada, mas apenas terreno ou quintal'), ('Não encanada', 'Não encanada')])),
                ('lixo_destino', models.TextField(choices=[('Coletado pela prefeitura', 'Coletado pela prefeitura'), ('Coletado por empresa particular', 'Coletado por empresa particular'), ('Queimado', 'Queimado'), ('Enterrado', 'Enterrado'), ('Jogado em terreno baldio', 'Jogado em terreno baldio'), ('Jogado em rio, lago, córrego ou represa', 'Jogado em rio, lago, córrego ou represa'), ('Outro', 'Outro')])),
                ('energia_eletrica', models.BooleanField(default=False)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proprietário', to='censo.morador')),
            ],
        ),
    ]
