# Generated by Django 5.2 on 2025-05-14 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0004_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='distrito',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicilio',
            name='municipio',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicilio',
            name='setor',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicilio',
            name='subdistrito',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='censo.morador'),
        ),
    ]
