# Generated by Django 5.2 on 2025-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0005_domicilio_distrito_domicilio_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
