# Generated by Django 5.2 on 2025-06-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0006_alter_domicilio_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='subdistrito',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='banheiros_com_chuveiro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='banheiros_sem_chuveiro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='chega_conexao_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='condicao_imovel',
            field=models.TextField(choices=[('ainda_pagando', 'Ainda pagando'), ('alugado', 'Alugado'), ('por_empregador', 'Por empregador'), ('por_familiar', 'Por familiar'), ('outra_forma', 'Outra forma'), ('outra_condicao', 'Outra condição'), ('ja_pago_herdado_ou_ganho', 'Já pago, herdado ou ganho')], default='outra_condicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicilio',
            name='lixo_quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='principais_demandas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quantidade_dormitorios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quem_respondeu_email',
            field=models.EmailField(default='Vinicius', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quem_respondeu_nome',
            field=models.CharField(default='vinicius', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quem_respondeu_telefone',
            field=models.CharField(default='120120012', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicilio',
            name='relacao_outras_ilhas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='rua',
            field=models.TextField(choices=[('R. Marina do Sol', 'R. Marina do Sol'), ('R. Marina do Frade', 'R. Marina do Frade'), ('R. Marina dos Coqueiros', 'R. Marina dos Coqueiros'), ('R. Marina da Lua', 'R. Marina da Lua'), ('R. Marina do Bosque', 'R. Marina do Bosque'), ('R. Marina Porto Bali', 'R. Marina Porto Bali'), ('R. Marina das Flores', 'R. Marina das Flores'), ('R. Marina das Estrelas', 'R. Marina das Estrelas'), ('R. Marina Ponta Leste', 'R. Marina Ponta Leste')], default='R. Marina do Sol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domicilio',
            name='tem_maquina_lavar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='atividade_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='carteira_assinada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='curso_frequentado',
            field=models.CharField(blank=True, choices=[('pre_escola', 'Pré-escola'), ('creche', 'Creche'), ('alfabetizacao_jovens_adultos', 'Alfabetização de jovens e adultos'), ('ensino_fundamental', 'Regular do ensino fundamental'), ('eja_fundamental', 'EJA do ensino fundamental'), ('ensino_medio', 'Regular do ensino médio'), ('superior_graduacao', 'Superior de graduação'), ('eja_medio', 'EJA do ensino médio'), ('especializacao', 'Especialização de nível superior'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('nenhum', 'Nenhum')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='diagnostico_autismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='diagnostico_deficiencia_andar',
            field=models.CharField(blank=True, choices=[('nao_consegue', 'Tem, não consegue de modo algum'), ('muita_dificuldade', 'Tem muita dificuldade'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('sem_dificuldade', 'Não tem dificuldade')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='diagnostico_deficiencia_visao',
            field=models.CharField(blank=True, choices=[('nao_consegue', 'Tem, não consegue de modo algum'), ('muita_dificuldade', 'Tem muita dificuldade'), ('alguma_dificuldade', 'Tem alguma dificuldade'), ('sem_dificuldade', 'Não tem dificuldade')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='empresa_registrada_cnpj',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='faixa_rendimento',
            field=models.CharField(blank=True, choices=[('faixa_1', 'R$1,00 a R$500,00'), ('faixa_2', 'R$501,00 a R$1.000,00'), ('faixa_3', 'R$1.001,00 a R$2.000,00'), ('faixa_4', 'R$2.001,00 a R$3.000,00'), ('faixa_5', 'R$3.001,00 a R$5.000,00'), ('faixa_6', 'R$5.001,00 a R$10.000,00'), ('faixa_7', 'R$10.001,00 a R$20.000,00'), ('faixa_8', 'R$20.001,00 a R$100.000,00'), ('faixa_9', 'R$100.001,00 ou mais')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='frequenta_escola',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao_mas_ja_frequentou', 'Não, mas já frequentou'), ('nunca_frequentou', 'Não, nunca frequentou')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='ja_concluiu_outro_superior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='meio_transporte_trabalho',
            field=models.CharField(blank=True, choices=[('a_pe', 'A pé'), ('bicicleta', 'Bicicleta'), ('motocicleta', 'Motocicleta'), ('mototaxi', 'Mototáxi'), ('automovel', 'Automóvel'), ('taxi', 'Táxi ou similares'), ('van_perua', 'Van, perua ou similares'), ('onibus', 'Ônibus'), ('caminhao_adaptado', 'Caminhonete ou caminhão adaptado'), ('embarcacao_grande', 'Embarcação de médio/grande porte'), ('embarcacao_pequena', 'Embarcação de pequeno porte'), ('outros', 'Outros')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='possui_conjuge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='quantidade_trabalhos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='registro_nascimento',
            field=models.CharField(blank=True, choices=[('cartorio', 'Registro em cartório'), ('registro_indigena', 'Registro administrativo de nascimento indígena'), ('nao_tem', 'Não tem'), ('nao_sabe', 'Não sabe')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='tipo_uniao',
            field=models.CharField(blank=True, choices=[('casamento_civil_religioso', 'Casamento civil e religioso'), ('casamento_civil', 'Só casamento civil'), ('casamento_religioso', 'Só casamento religioso'), ('uniao_consensual', 'União consensual')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='trabalhou_atividade_remunerada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='vinculo_domiciliar',
            field=models.TextField(choices=[('responsavel_domicilio', 'Pessoa responsável pelo domicílio'), ('conjuge_diferente_sexo', 'Cônjuge ou companheiro(a) de sexo diferente'), ('conjuge_mesmo_sexo', 'Cônjuge ou companheiro(a) do mesmo sexo'), ('filho_responsavel_e_conjuge', 'Filho(a) do responsável e do cônjuge'), ('filho_somente_responsavel', 'Filho(a) somente do responsável'), ('genro_nora', 'Genro ou nora'), ('pai_mae_padrasto_madrasta', 'Pai, mãe, padrasto ou madrasta'), ('sogro_sogra', 'Sogro(a)'), ('neto_neta', 'Neto(a)'), ('enteado_enteada', 'Enteado(a)'), ('irmao_irma', 'Irmão ou irmã'), ('avo_avos', 'Avô ou avó'), ('outro_parente', 'Outro parente'), ('agregado', 'Agregado(a)'), ('bisneto_bisneta', 'Bisneto(a)'), ('pensionista', 'Pensionista'), ('empregado_domestico', 'Empregado(a) doméstico(a)'), ('parente_empregado_domestico', 'Parente do(a) empregado(a) doméstico(a)'), ('individual_domicilio_coletivo', 'Individual em domicílio coletivo')], default='responsavel_domicilio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morador',
            name='vive_com_conjuge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='numero',
            field=models.TextField(),
        ),
    ]
